# Generated by Django 5.2.11 on 2026-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_alter_pedido_fecha_alter_servicio_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='cif_nif',
            field=models.CharField(default='00000000X', max_length=20, unique=True, verbose_name='CIF/NIF'),
            preserve_default=False,
        ),
    ]
