# Generated by Django 5.2.11 on 2026-04-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0008_alter_detallepedido_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
