# Generated by Django 5.2.11 on 2026-04-03 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0009_servicio_cp_servicio_lat_servicio_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cp', models.CharField(max_length=5)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitud_ayuda',
            },
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='buscador.establecimiento'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('id_establecimiento', 'id_usuario')},
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=5)),
                ('dias_disponibles', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_voluntario', to='buscador.usuario')),
            ],
            options={
                'db_table': 'voluntario',
            },
        ),
    ]
