# Generated by Django 5.2.11 on 2026-04-03 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0010_solicitudayuda_alter_valoracion_id_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudayuda',
            name='encuesta_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='requiere_llamada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='buscador.solicitudayuda')),
            ],
            options={
                'db_table': 'encuesta_satisfaccion',
            },
        ),
    ]
