"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv  # busca un archivo secreto llamado .env y lo carga
import environ  # permite leer variables y decirles qué tipo de dato son
import dj_database_url  # permite configurar la base de datos usando una URL, útil para despliegues como Railway
import os  # permite que Python lea los valores .env
import json

env = environ.Env(DEBUG=(bool, False))
BASE_DIR = (
    Path(__file__).resolve().parent.parent
)  # BASE_DIR utilizando la librería pathlib para obtener la ruta absoluta de la raíz del proyecto de forma dinámica

if os.path.exists(os.path.join(BASE_DIR, ".env")):
    environ.Env.read_env(
        os.path.join(BASE_DIR, ".env")
    )  # lo separa en partes y lo carga, para que luego podamos usarlo con env("NOMBRE_VARIABLE") por seguridad


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
GOOGLE_MAPS_API_KEY = env("GOOGLE_MAPS_API_KEY", default="")
# Busca en el sistema operativo una variable llamada así

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="clave-segura-solo-para-el-paso-de-build")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# ALLOWED_HOSTS = env.list("ALLOWED_HOSTS",default=["127.0.0.1", "localhost",".railway.app"])
ALLOWED_HOSTS = ["*"]
DEBUG = True

AUTH_USER_MODEL = "users.CustomUser"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "buscador",
    "users",
    "knox",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database. Intenta usar la URL de la base de datos proporcionada por Railway, si no está disponible, usa variables de .env
#db_from_env = env.db_url("DATABASE_URL", default=None)

print(f"DEBUG: Intentando conectar a HOST: {os.environ.get('DB_HOST')}")


DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    #  PRODUCCIÓN (Railway)
    DATABASES = {
        "default": env.db_url("DATABASE_URL")
    }
else:
    #  LOCAL (Docker)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST", 'db'),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


"""if os.environ.get("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", default=""),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT"),
            
        }
    } """
""" else:
    # Este bloque salva el "Build" de quedarse colgado
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    } """
    # Si no hay DATABASE_URL, usamos la configuración local de PostgreSQL

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "https://app-comercio-red.vercel.app",
    "http://localhost:5173",
    "http://localhost:3000",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    "https://app-comercio-red.vercel.app",
    "https://proyecto-daw-production.up.railway.app",
    "https://*.vercel.app",
    "https://*.up.railway.app",
    "http://localhost:5173",
]

# Configuración de Django REST Framework para usar JWT y permitir cualquier permiso
APPEND_SLASH = True
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

# Duración de Tokens
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# CONFIGURACIÓN DE EMAIL
# para pruebas para ver los emails de matching
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# para mandar emails reales
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")


google_creds_env = os.getenv("GOOGLE_ANALYTICS_JSON")

if google_creds_env:
    # Si estamos en la nube, convertimos el texto de la variable en un diccionario
    GOOGLE_ANALYTICS_CREDENTIALS = json.loads(google_creds_env)
else:
    # Si estamos en local, usamos la ruta al archivo físico
    GOOGLE_ANALYTICS_CREDENTIALS = os.path.join(
        BASE_DIR, "credentials", "google-analytics-key.json"
    )

GOOGLE_ANALYTICS_PROPERTY_ID = os.getenv("GOOGLE_ANALYTICS_PROPERTY_ID")
