# Generated by Django 5.2.11 on 2026-03-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercio', models.CharField()),
                ('categoria', models.CharField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, null=True)),
                ('cp', models.CharField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('url_web', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'establecimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('apellidos', models.CharField()),
                ('correo', models.CharField(unique=True)),
                ('auth_id', models.CharField(unique=True)),
                ('sexo', models.CharField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, null=True)),
                ('piso', models.CharField(blank=True, null=True)),
                ('letra', models.CharField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, null=True)),
                ('cp', models.CharField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('importe_total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('metodo_entrega', models.CharField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, null=True)),
                ('id_establecimiento', models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.establecimiento')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.usuario')),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(blank=True, null=True)),
                ('producto', models.CharField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=5, max_digits=10)),
                ('id_establecimiento', models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.establecimiento')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=5, max_digits=10)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.pedido')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, null=True)),
                ('precio_hora', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('fecha_creacion', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.usuario')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField()),
                ('categoria', models.CharField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, null=True)),
                ('publico_objetivo', models.CharField(blank=True, null=True)),
                ('rol_evento', models.CharField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.usuario')),
            ],
            options={
                'db_table': 'evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_establecimiento', models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.establecimiento')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buscador.usuario')),
            ],
            options={
                'db_table': 'valoracion',
                'managed': True,
            },
        ),
    ]
