# Generated by Django 5.2.11 on 2026-04-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cp', models.CharField(max_length=5)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('encuesta_enviada', models.BooleanField(default=False)),
                ('requiere_llamada', models.BooleanField(default=False)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud_ayuda',
            },
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('id_establecimiento', 'id_usuario')},
        ),
        migrations.AddField(
            model_name='valoracion',
            name='id_servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='buscador.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('id_establecimiento', 'id_usuario'), ('id_servicio', 'id_usuario')},
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='buscador.solicitudayuda')),
            ],
            options={
                'db_table': 'encuesta_satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=5)),
                ('dias_disponibles', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_voluntario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voluntario',
            },
        ),
    ]
