# Generated by Django 5.2.11 on 2026-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_establecimiento_subcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
