# Generated by Django 5.2.11 on 2026-04-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_solicitudayuda_alter_valoracion_unique_together_and_more'),
        ('buscador', '0002_solicitudayuda_encuestasatisfaccion_voluntario'),
    ]

    operations = [
    ]
