# Generated by Django 5.2.11 on 2026-03-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0006_establecimiento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.pedido'),
        ),
    ]
