# Generated by Django 5.2.11 on 2026-03-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_alter_detallepedido_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.producto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='buscador.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.establecimiento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='buscador.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.establecimiento'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='buscador.usuario'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.establecimiento'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='buscador.usuario'),
        ),
    ]
