# Generated by Django 6.0.3 on 2026-04-07 15:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0009_servicio_cp_servicio_lat_servicio_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='id_establecimiento',
            field=models.ForeignKey(blank=True, db_column='id_establecimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='buscador.establecimiento'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('id_establecimiento', 'id_usuario')},
        ),
    ]
