# Generated by Django 5.2.11 on 2026-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
