# Generated by Django 5.2.11 on 2026-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_cif_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cif_nif',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='DNI o CIF'),
            preserve_default=False,
        ),
    ]
