# Generated by Django 5.2.11 on 2026-05-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_birthday_customuser_fecha_nacimiento_and_more'),
        ('users', '0003_alter_customuser_cif_nif'),
    ]

    operations = [
    ]
