# Generated by Django 5.2.11 on 2026-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260419_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cif_nif',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
