# Generated by Django 5.2.11 on 2026-05-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_cif_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cif_nif',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
